### ISSUE TITLE
What is the name of this algorithm

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-vinnie1234#1]
I would like to know the name of this sorting algorithm. Can you find a reference to a description of this algorithm?

**Comment by vinnie1234** [comment]
Het gaat hier om een "Insertion sort" als ik het goed heb..

**Comment by dvberkel** [comment]
Bijna, insertion sort is een in-place algoritme. Dit betekend dat de oorspronkelijke array wordt gebruikt om het resultaat in op te slaan.

Dit kan gevolgen hebben voor de complexiteit. Denk bijvoorbeeld aan de Elm definitie van een lijst

```elm
type List a
    = Empty
    | Cons a (List a)
```

Een element aan het eind toevoegen kan een "dure" operatie zijn, waardoor de garanties van insertion sort niet meer kloppen.

**Comment by vinnie1234** [comment]
Ha daan,

Als ik jou commentaar goed begrijp gaat het hier niet om een Insertion Sort. Ik heb even verder gekeken en dank dat ook dat het hier gaat om een "Selection Sort"
